<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "alm_portfolio"
 *
 * Auto generated by Extension Builder 2014-06-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Portfolio',
	'description' => 'Portfolio - show your work',
	'category' => 'plugin',
	'author' => 'Andi Platen',
	'author_email' => 'info@wireframe.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.2.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
